{
    'name': 'Distribution Management - Routes',
    'version': '17.0.3.0.0',
    'summary': 'Adds Delivery Routes (ordered clients) and automatic tour generation',
    'description': '''
Module extension adding Routes (ordered distribution paths), Zones, and automation to generate Tours from Routes.
- Route model with ordered Route Lines (sequence)
- Zone model to group clients geographically
- Button to generate a Tour from a Route (creates distribution.tour and lines)
''',
    'author': 'Generated by ChatGPT',
    'category': 'Inventory/Delivery',
    'depends': ['base','sale','stock'],
    'data': [
        'security/ir.model.access.csv',
        'views/menu_views.xml',
        'views/route_views.xml',
        'data/route_demo.xml'
    ],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
