grant connect to CoursBDA;
grant dba to CoursBDA;
grant resource to CoursBDA;
grant unlimited tablespace to CoursBDA;


create table DEPT
( DEPTNO number(2) not null
constraint PK_DEPT primary key,
DNAME varchar2(14),
LOC varchar2 (13)
)

create table DEPT
( DEPTNO number(2) not null
constraint PK_DEPT primary key,
DNAME varchar2(14),
LOC varchar2 (13)
)

CREATE TABLE EMP
(
  EMPNO NUMBER(4) NOT NULL CONSTRAINT PK_EMP PRIMARY KEY,
  ENAME VARCHAR2(10),
  JOB VARCHAR2(9),
  MGR NUMBER(4),
  HIREDATE DATE,
  SAL NUMBER(7,2),
  COMM NUMBER(7,2),
  DEPTNO NUMBER(2),
  CONSTRAINT FK_DEPTNO FOREIGN KEY (DEPTNO) REFERENCES DEPT(DEPTNO)
);



INSERT INTO  DEPT VALUES (10,'ACCOUNTING', 'NEW YORK');
INSERT INTO  DEPT VALUES (20,'RESEARCH', 'DALLAS');
INSERT INTO  DEPT VALUES (30,'SALES', 'CHIACAGO');
INSERT INTO  DEPT VALUES (40,'OPERATIONS', 'BOSTON');


INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (7369, 'SMITH', 'CLERK', 7902, TO_DATE('17-12-1980','DD-MM-YYYY'), 800, NULL, 20);

INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (7499, 'ALLEN', 'SALESMAN', 7698, TO_DATE('20-02-1981','DD-MM-YYYY'), 1600, 300, 30);

INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (7521, 'WARD', 'SALESMAN', 7698, TO_DATE('22-02-1981','DD-MM-YYYY'), 1250, 500, 30);

INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (7566, 'JONES', 'MANAGER', 7839, TO_DATE('02-04-1981','DD-MM-YYYY'), 2975, NULL, 20);

INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (7654, 'MARTIN', 'SALESMAN', 7698, TO_DATE('28-09-1981','DD-MM-YYYY'), 1250, 1400, 30);

INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (7698, 'BLAKE', 'MANAGER', 7839, TO_DATE('01-05-1981','DD-MM-YYYY'), 2850, NULL, 30);

INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (7782, 'CLARK', 'MANAGER', 7839, TO_DATE('09-06-1981','DD-MM-YYYY'), 2450, NULL, 10);


select ENAME, SAL, COMM, SAL+COMM
from EMP
where JOB = 'CLERK';

select ENAME, COMM, SAL
from EMP
where JOB = 'CLERK'
order by COMM desc, SAL desc;

select ENAME, COMM, SAL
from EMP
where JOB = 'CLERK' and COMM < 0.25*SAL;

select count(*)
from EMP
where DEPTNO = 10;

select count(*)
from EMP
where COMM is not null;

select count(distinct JOB)
from EMP;

select JOB, avg(SAL)
from EMP
group by JOB;

select sum(SAL)
from EMP, DEPT
where EMP.DEPTNO = DEPT.DEPTNO
and DNAME = 'SALES';

select ENAME, DNAME
from EMP, DEPT
where EMP.DEPTNO = DEPT.DEPTNO;
select ENAME
from EMP
where SAL > (select SAL from EMP where ENAME = 'ALLEN');
